replicaCount: 1

image:
  repository: quang1709/data-hub
  pullPolicy: Always
  tag: "latest"

service:
  type: NodePort
  port: 3002
  targetPort: 3002
  nodePort: 30008

resources:
  limits:
    cpu: "400m"
    memory: "512Mi"
  requests:
    cpu: "100m"
    memory: "256Mi"

ingress:
  enabled: false

serviceAccount:
  create: true
  name: "data-hub-sa"
autoscaling:
  enabled: false
